a = input("Введите сторону а:")
a = int(a)
b = input("Введите сторону b:")
b = int(b)
c = input("Введите сторону c:")
c = int(c)
h = input("Введите высоту h:")
h = int(h)
res = (a + b + c)
S = (1/2 * a * h)
print("Периметр трикутника:", res)
print("Площа трикутника", S)